---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wdk.
--- DateTime: 2026/9/21 16:54
---

--- 比较线程标识与所中的是否一致,一致则释放锁
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0